#version 450 core

layout(local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

layout(binding = 0, offset = 0) uniform atomic_uint counter0;
layout(rgba32f, binding = 0) uniform writeonly image2D o_out0;

void main()
{
    atomicCounterIncrement(counter0);
    const uint counterValue = atomicCounter(counter0);
    imageStore(o_out0, ivec2(0, 0), vec4(float(counterValue), float(counterValue), float(counterValue), 1.0));
}
