include(GNUInstallDirs)

set(RAWGL_LINUX_PREFIX "" CACHE PATH "Optional Linux dependency prefix prepended to CMAKE_PREFIX_PATH.")
set(RAWGL_WINDOWS_DEPS_ROOT "" CACHE PATH "Optional Windows dependency root for legacy static-library fallback discovery.")
set(RAWGL_WINDOWS_IMPORTED_CONFIG_REWRITE_ROOTS "" CACHE STRING "Optional semicolon-separated stale roots to rewrite in imported Windows package configs.")
set(RAWGL_WINDOWS_DNG_SDK_ROOT "" CACHE PATH "Optional Windows DNG SDK root used to resolve dng_sdk.lib for static builds.")
set(RAWGL_WINDOWS_DNG_LIBRARY_RELEASE "" CACHE FILEPATH "Windows release DNG SDK library")
set(RAWGL_WINDOWS_DNG_LIBRARY_DEBUG "" CACHE FILEPATH "Windows debug DNG SDK library")
set(RAWGL_WINDOWS_XMP_CORE_LIBRARY_RELEASE "" CACHE FILEPATH "Windows release XMP core library")
set(RAWGL_WINDOWS_XMP_CORE_LIBRARY_DEBUG "" CACHE FILEPATH "Windows debug XMP core library")
set(RAWGL_WINDOWS_XMP_FILES_LIBRARY_RELEASE "" CACHE FILEPATH "Windows release XMP files library")
set(RAWGL_WINDOWS_XMP_FILES_LIBRARY_DEBUG "" CACHE FILEPATH "Windows debug XMP files library")
set(RAWGL_WINDOWS_CONFIGURATION_TYPES "Debug;Release" CACHE STRING "Windows multi-config generator configurations. Leave empty to keep the generator default.")
set(RAWGL_MINIPLY_INCLUDE_DIR "${CMAKE_CURRENT_SOURCE_DIR}/src/third_party/miniply" CACHE PATH "Directory containing miniply.h")
option(RAWGL_WINDOWS_UTF8 "Compile all Windows/MSVC targets with /utf-8." ON)
option(RAWGL_WINDOWS_PREFIX_ONLY_FIND "Restrict Windows third-party dependency discovery to CMake/package prefix paths and explicit hints." ON)
set(RAWGL_WINDOWS_DEBUG_SUFFIX "d" CACHE STRING "Suffix applied to Windows Debug target output names.")
option(RAWGL_BUILD_APP "Build the RawGL command-line application." ON)
option(RAWGL_BUILD_DOCS "Build Doxygen documentation targets." OFF)
option(RAWGL_BUILD_SPHINX_DOCS "Build the Sphinx HTML documentation site (requires Doxygen XML)." OFF)
option(RAWGL_DOCS_ONLY "Configure only documentation targets and skip RawGL dependency/target discovery." OFF)
option(RAWGL_BUILD_PYTHON "Build Python bindings with nanobind." OFF)
option(RAWGL_BUILD_WHEEL "Add a `rawgl_wheel` target (Python wheel build)." OFF)
option(RAWGL_WHEEL_NO_BUILD_ISOLATION "Build wheel without isolation (requires scikit-build-core installed)." OFF)
option(RAWGL_INSTALL_DEV_ARTIFACTS "Install C++ headers, libraries, and CMake package files." ON)
option(RAWGL_LINUX_USE_LIBCXX "Use libc++ instead of libstdc++ for Linux Clang builds." OFF)
if(WIN32)
    set(_rawgl_use_packaged_miniply_default ON)
else()
    set(_rawgl_use_packaged_miniply_default OFF)
endif()
option(RAWGL_USE_PACKAGED_MINIPLY "Prefer package target miniply::miniply over the vendored copy." ${_rawgl_use_packaged_miniply_default})
if(WIN32)
    set(_rawgl_python_bind_core_default ON)
else()
    set(_rawgl_python_bind_core_default OFF)
endif()
option(RAWGL_PYTHON_BIND_CORE "Link the Python module against the real RawGL workflow facade instead of scaffold-only mode." ${_rawgl_python_bind_core_default})
set(RAWGL_PYTHON_EXECUTABLE "" CACHE FILEPATH "Override Python interpreter used for RawGL bindings.")
set(RAWGL_PYTHON_INCLUDE_DIR "" CACHE PATH "Override Python include directory used for RawGL bindings.")
set(RAWGL_PYTHON_LIBRARY_RELEASE "" CACHE FILEPATH "Override release Python import library used for RawGL bindings on Windows multiconfig builds.")
set(RAWGL_PYTHON_LIBRARY_DEBUG "" CACHE FILEPATH "Override debug Python import library used for RawGL bindings on Windows multiconfig builds.")

if(RAWGL_PYTHON_EXECUTABLE)
    if(NOT EXISTS "${RAWGL_PYTHON_EXECUTABLE}")
        message(FATAL_ERROR "RAWGL_PYTHON_EXECUTABLE does not exist: ${RAWGL_PYTHON_EXECUTABLE}")
    endif()
    set(Python_EXECUTABLE "${RAWGL_PYTHON_EXECUTABLE}" CACHE FILEPATH "Python interpreter" FORCE)
endif()

if(RAWGL_PYTHON_INCLUDE_DIR)
    if(NOT IS_ABSOLUTE "${RAWGL_PYTHON_INCLUDE_DIR}")
        message(FATAL_ERROR "RAWGL_PYTHON_INCLUDE_DIR must be an absolute path: ${RAWGL_PYTHON_INCLUDE_DIR}")
    endif()
    if(NOT EXISTS "${RAWGL_PYTHON_INCLUDE_DIR}")
        message(FATAL_ERROR "RAWGL_PYTHON_INCLUDE_DIR does not exist: ${RAWGL_PYTHON_INCLUDE_DIR}")
    endif()
    set(Python_INCLUDE_DIR "${RAWGL_PYTHON_INCLUDE_DIR}" CACHE PATH "Python include directory" FORCE)
endif()

foreach(_rawgl_python_lib_var IN ITEMS RAWGL_PYTHON_LIBRARY_RELEASE RAWGL_PYTHON_LIBRARY_DEBUG)
    if(${_rawgl_python_lib_var})
        if(NOT IS_ABSOLUTE "${${_rawgl_python_lib_var}}")
            message(FATAL_ERROR "${_rawgl_python_lib_var} must be an absolute path: ${${_rawgl_python_lib_var}}")
        endif()
        if(NOT EXISTS "${${_rawgl_python_lib_var}}")
            message(FATAL_ERROR "${_rawgl_python_lib_var} does not exist: ${${_rawgl_python_lib_var}}")
        endif()
    endif()
endforeach()

function(rawgl_cache_prepend_prefix_path prefix_path)
    if(NOT prefix_path)
        return()
    endif()

    set(rawgl_prefix_list ${CMAKE_PREFIX_PATH})
    list(REMOVE_ITEM rawgl_prefix_list "${prefix_path}")
    list(PREPEND rawgl_prefix_list "${prefix_path}")
    set(CMAKE_PREFIX_PATH "${rawgl_prefix_list}" CACHE STRING "Search path for external dependencies." FORCE)
endfunction()

if(WIN32)
    rawgl_cache_prepend_prefix_path("${RAWGL_WINDOWS_DEPS_ROOT}")
    if(CMAKE_CONFIGURATION_TYPES AND RAWGL_WINDOWS_CONFIGURATION_TYPES)
        set(CMAKE_CONFIGURATION_TYPES "${RAWGL_WINDOWS_CONFIGURATION_TYPES}" CACHE STRING "RawGL Windows generator configurations." FORCE)
    endif()
    set(CMAKE_FIND_PACKAGE_PREFER_CONFIG ON CACHE BOOL "Prefer package config files over Find modules on Windows static builds." FORCE)
    set(CMAKE_FIND_USE_PACKAGE_REGISTRY OFF CACHE BOOL "Do not use the user package registry for RawGL Windows dependency discovery." FORCE)
    set(CMAKE_FIND_USE_SYSTEM_PACKAGE_REGISTRY OFF CACHE BOOL "Do not use the system package registry for RawGL Windows dependency discovery." FORCE)
    set(CMAKE_MAP_IMPORTED_CONFIG_RELWITHDEBINFO Release CACHE STRING "Map RelWithDebInfo imports to Release on Windows static builds." FORCE)
    set(CMAKE_MAP_IMPORTED_CONFIG_MINSIZEREL Release CACHE STRING "Map MinSizeRel imports to Release on Windows static builds." FORCE)
    set(CMAKE_MSVC_RUNTIME_LIBRARY
        "$<$<CONFIG:Debug>:MultiThreadedDebug>$<$<NOT:$<CONFIG:Debug>>:MultiThreaded>"
        CACHE STRING "MSVC runtime library selection." FORCE)
elseif(CMAKE_SYSTEM_NAME STREQUAL "Linux")
    rawgl_cache_prepend_prefix_path("${RAWGL_LINUX_PREFIX}")
    set(CMAKE_POSITION_INDEPENDENT_CODE ON CACHE BOOL "Build position independent code on Linux." FORCE)
endif()

if(MSVC AND RAWGL_WINDOWS_UTF8)
    add_compile_options(/utf-8)
endif()

if(RAWGL_BUILD_SPHINX_DOCS AND NOT RAWGL_BUILD_DOCS)
    set(RAWGL_BUILD_DOCS ON CACHE BOOL "Build Doxygen documentation targets." FORCE)
endif()

if(RAWGL_DOCS_ONLY)
    set(RAWGL_BUILD_APP OFF CACHE BOOL "Build the RawGL command-line application." FORCE)
    set(RAWGL_BUILD_PYTHON OFF CACHE BOOL "Build Python bindings with nanobind." FORCE)
    set(RAWGL_BUILD_WHEEL OFF CACHE BOOL "Add a `rawgl_wheel` target (Python wheel build)." FORCE)
    set(BUILD_TESTING OFF CACHE BOOL "Build testing targets." FORCE)
endif()
