include_guard(GLOBAL)

function(rawgl_report_dependency name enabled found provider)
    if(NOT enabled)
        message(STATUS "    ${name}: OFF (not required)")
        return()
    endif()

    if(found)
        if(provider)
            message(STATUS "    ${name}: FOUND (${provider})")
        else()
            message(STATUS "    ${name}: FOUND")
        endif()
    else()
        message(STATUS "    ${name}: NOTFOUND")
    endif()
endfunction()

function(rawgl_any_target_found out_var)
    set(_found OFF)
    set(_provider "")
    foreach(_target_name ${ARGN})
        if(_target_name AND TARGET ${_target_name})
            set(_found ON)
            set(_provider "target ${_target_name}")
            break()
        endif()
    endforeach()
    set(${out_var} "${_found}" PARENT_SCOPE)
    set(${out_var}_PROVIDER "${_provider}" PARENT_SCOPE)
endfunction()

function(rawgl_path_found out_var path_value provider_prefix)
    if(path_value)
        set(${out_var} ON PARENT_SCOPE)
        set(${out_var}_PROVIDER "${provider_prefix}${path_value}" PARENT_SCOPE)
    else()
        set(${out_var} OFF PARENT_SCOPE)
        set(${out_var}_PROVIDER "" PARENT_SCOPE)
    endif()
endfunction()

function(rawgl_report_file_dependency name path_value)
    if(path_value AND EXISTS "${path_value}")
        rawgl_report_dependency("${name}" ON ON "${path_value}")
    else()
        rawgl_report_dependency("${name}" ON OFF "")
    endif()
endfunction()

function(rawgl_print_config_summary)
    message(STATUS "RawGL configuration summary:")
    message(STATUS "  Generator: ${CMAKE_GENERATOR}")
    if(CMAKE_CONFIGURATION_TYPES)
        message(STATUS "  Configurations: ${CMAKE_CONFIGURATION_TYPES}")
    else()
        if(CMAKE_BUILD_TYPE)
            message(STATUS "  Build type: ${CMAKE_BUILD_TYPE}")
        else()
            message(STATUS "  Build type: <not set>")
        endif()
    endif()
    message(STATUS "  C++ compiler: ${CMAKE_CXX_COMPILER_ID} ${CMAKE_CXX_COMPILER_VERSION}")
    message(STATUS "  C++ compiler path: ${CMAKE_CXX_COMPILER}")
    if(CMAKE_PREFIX_PATH)
        message(STATUS "  CMAKE_PREFIX_PATH: ${CMAKE_PREFIX_PATH}")
    else()
        message(STATUS "  CMAKE_PREFIX_PATH: <empty>")
    endif()

    if(WIN32)
        message(STATUS "  RAWGL_WINDOWS_DEPS_ROOT: ${RAWGL_WINDOWS_DEPS_ROOT}")
    elseif(CMAKE_SYSTEM_NAME STREQUAL "Linux")
        if(RAWGL_LINUX_PREFIX)
            message(STATUS "  RAWGL_LINUX_PREFIX: ${RAWGL_LINUX_PREFIX}")
        else()
            message(STATUS "  RAWGL_LINUX_PREFIX: <empty>")
        endif()
    endif()

    message(STATUS "  Options:")
    message(STATUS "    RAWGL_WINDOWS_UTF8: ${RAWGL_WINDOWS_UTF8}")
    message(STATUS "    RAWGL_BUILD_APP: ${RAWGL_BUILD_APP}")
    message(STATUS "    RAWGL_BUILD_DOCS: ${RAWGL_BUILD_DOCS}")
    message(STATUS "    RAWGL_BUILD_SPHINX_DOCS: ${RAWGL_BUILD_SPHINX_DOCS}")
    message(STATUS "    RAWGL_DOCS_ONLY: ${RAWGL_DOCS_ONLY}")
    if(WIN32)
        message(STATUS "    RAWGL_WINDOWS_PREFIX_ONLY_FIND: ${RAWGL_WINDOWS_PREFIX_ONLY_FIND}")
        message(STATUS "    RAWGL_WINDOWS_CONFIGURATION_TYPES: ${RAWGL_WINDOWS_CONFIGURATION_TYPES}")
        message(STATUS "    RAWGL_WINDOWS_DEBUG_SUFFIX: ${RAWGL_WINDOWS_DEBUG_SUFFIX}")
    endif()
    message(STATUS "    RAWGL_BUILD_PYTHON: ${RAWGL_BUILD_PYTHON}")
    message(STATUS "    RAWGL_BUILD_WHEEL: ${RAWGL_BUILD_WHEEL}")
    message(STATUS "    RAWGL_WHEEL_NO_BUILD_ISOLATION: ${RAWGL_WHEEL_NO_BUILD_ISOLATION}")
    message(STATUS "    RAWGL_INSTALL_DEV_ARTIFACTS: ${RAWGL_INSTALL_DEV_ARTIFACTS}")
    if(CMAKE_SYSTEM_NAME STREQUAL "Linux")
        message(STATUS "    RAWGL_LINUX_USE_LIBCXX: ${RAWGL_LINUX_USE_LIBCXX}")
    endif()
    message(STATUS "    RAWGL_USE_PACKAGED_MINIPLY: ${RAWGL_USE_PACKAGED_MINIPLY}")
    message(STATUS "    RAWGL_PYTHON_BIND_CORE: ${RAWGL_PYTHON_BIND_CORE}")
    if(RAWGL_PYTHON_EXECUTABLE)
        message(STATUS "    RAWGL_PYTHON_EXECUTABLE: ${RAWGL_PYTHON_EXECUTABLE}")
    endif()
    if(RAWGL_PYTHON_INCLUDE_DIR)
        message(STATUS "    RAWGL_PYTHON_INCLUDE_DIR: ${RAWGL_PYTHON_INCLUDE_DIR}")
    endif()
    if(RAWGL_PYTHON_LIBRARY_RELEASE)
        message(STATUS "    RAWGL_PYTHON_LIBRARY_RELEASE: ${RAWGL_PYTHON_LIBRARY_RELEASE}")
    endif()
    if(RAWGL_PYTHON_LIBRARY_DEBUG)
        message(STATUS "    RAWGL_PYTHON_LIBRARY_DEBUG: ${RAWGL_PYTHON_LIBRARY_DEBUG}")
    endif()

    message(STATUS "  Dependencies:")
    if(RAWGL_DOCS_ONLY)
        message(STATUS "    Docs-only configure: core dependency discovery skipped.")
        return()
    endif()
    message(STATUS "    Core:")

    rawgl_any_target_found(_rawgl_threads_found Threads::Threads)
    rawgl_report_dependency("Threads" ON "${_rawgl_threads_found}" "${_rawgl_threads_found_PROVIDER}")

    set(_rawgl_opengl_found OFF)
    set(_rawgl_opengl_provider "")
    if(TARGET OpenGL::OpenGL AND TARGET OpenGL::GLX)
        set(_rawgl_opengl_found ON)
        set(_rawgl_opengl_provider "targets OpenGL::OpenGL, OpenGL::GLX")
    elseif(TARGET OpenGL::GL)
        set(_rawgl_opengl_found ON)
        set(_rawgl_opengl_provider "target OpenGL::GL")
    elseif(DEFINED OpenGL_FOUND AND OpenGL_FOUND)
        set(_rawgl_opengl_found ON)
        set(_rawgl_opengl_provider "find_package(OpenGL)")
    elseif(DEFINED OPENGL_FOUND AND OPENGL_FOUND)
        set(_rawgl_opengl_found ON)
        set(_rawgl_opengl_provider "find_package(OpenGL)")
    endif()
    rawgl_report_dependency("OpenGL" ON "${_rawgl_opengl_found}" "${_rawgl_opengl_provider}")

    if(CMAKE_SYSTEM_NAME STREQUAL "Linux")
        rawgl_any_target_found(_rawgl_x11_found X11::X11)
        if(NOT _rawgl_x11_found AND X11_FOUND)
            set(_rawgl_x11_found ON)
            set(_rawgl_x11_found_PROVIDER "find_package(X11)")
        endif()
        rawgl_report_dependency("X11" ON "${_rawgl_x11_found}" "${_rawgl_x11_found_PROVIDER}")
    endif()

    rawgl_any_target_found(_rawgl_glew_found ${RAWGL_OPENGL_LOADER_TARGET})
    rawgl_report_dependency("GLEW" ON "${_rawgl_glew_found}" "${_rawgl_glew_found_PROVIDER}")

    rawgl_any_target_found(_rawgl_glfw_found ${RAWGL_GLFW_TARGET})
    rawgl_report_dependency("GLFW" ON "${_rawgl_glfw_found}" "${_rawgl_glfw_found_PROVIDER}")

    set(_rawgl_oiio_found OFF)
    set(_rawgl_oiio_provider "")
    if(TARGET OpenImageIO::OpenImageIO AND TARGET OpenImageIO::OpenImageIO_Util)
        set(_rawgl_oiio_found ON)
        set(_rawgl_oiio_provider "targets OpenImageIO::OpenImageIO, OpenImageIO::OpenImageIO_Util")
    endif()
    rawgl_report_dependency("OpenImageIO" ON "${_rawgl_oiio_found}" "${_rawgl_oiio_provider}")

    rawgl_path_found(_rawgl_spdlog_found "${RAWGL_SPDLOG_INCLUDE_DIR}" "")
    rawgl_report_dependency("spdlog" ON "${_rawgl_spdlog_found}" "${_rawgl_spdlog_found_PROVIDER}")

    rawgl_path_found(_rawgl_libraw_found "${RAWGL_LIBRAW_INCLUDE_DIR}" "")
    rawgl_report_dependency("libraw" ON "${_rawgl_libraw_found}" "${_rawgl_libraw_found_PROVIDER}")

    rawgl_any_target_found(_rawgl_openmeta_found OpenMeta::openmeta)
    rawgl_report_dependency("OpenMeta" ON "${_rawgl_openmeta_found}" "${_rawgl_openmeta_found_PROVIDER}")

    if(RAWGL_USE_PACKAGED_MINIPLY AND TARGET miniply::miniply)
        rawgl_report_dependency("miniply" ON ON "package target miniply::miniply")
    elseif(RAWGL_MINIPLY_SOURCES OR EXISTS "${RAWGL_MINIPLY_INCLUDE_DIR}/miniply.h")
        rawgl_report_dependency("miniply" ON ON "vendored fallback ${RAWGL_MINIPLY_INCLUDE_DIR}")
    else()
        rawgl_report_dependency("miniply" ON OFF "")
    endif()

    rawgl_any_target_found(_rawgl_rapidobj_found rapidobj::rapidobj)
    rawgl_report_dependency("rapidobj" ON "${_rawgl_rapidobj_found}" "${_rawgl_rapidobj_found_PROVIDER}")

    message(STATUS "    Platform extras:")

    if(CMAKE_SYSTEM_NAME STREQUAL "Linux")
        set(_rawgl_openexr_found OFF)
        if(DEFINED OpenEXR_FOUND AND OpenEXR_FOUND)
            set(_rawgl_openexr_found ON)
        elseif(TARGET OpenEXR::OpenEXR)
            set(_rawgl_openexr_found ON)
        endif()
        rawgl_report_dependency("OpenEXR" ON "${_rawgl_openexr_found}" "config/package")

        rawgl_any_target_found(_rawgl_bzip2_found BZip2::BZip2)
        rawgl_report_dependency("BZip2" ON "${_rawgl_bzip2_found}" "${_rawgl_bzip2_found_PROVIDER}")

        rawgl_any_target_found(_rawgl_fmt_found fmt::fmt)
        rawgl_report_dependency("fmt" ON "${_rawgl_fmt_found}" "${_rawgl_fmt_found_PROVIDER}")

        rawgl_any_target_found(_rawgl_freetype_found Freetype::Freetype)
        rawgl_report_dependency("freetype" ON "${_rawgl_freetype_found}" "${_rawgl_freetype_found_PROVIDER}")

        rawgl_any_target_found(_rawgl_pugixml_found pugixml::pugixml pugixml)
        rawgl_report_dependency("pugixml" ON "${_rawgl_pugixml_found}" "${_rawgl_pugixml_found_PROVIDER}")

        rawgl_any_target_found(_rawgl_gif_found GIF::GIF)
        rawgl_report_dependency("GIF/giflib" ON "${_rawgl_gif_found}" "${_rawgl_gif_found_PROVIDER}")

        rawgl_any_target_found(_rawgl_ptex_found Ptex::Ptex_static Ptex::Ptex Ptex)
        rawgl_report_dependency("Ptex" ON "${_rawgl_ptex_found}" "${_rawgl_ptex_found_PROVIDER}")

        set(_rawgl_dng_sdk_found OFF)
        if(DEFINED dng_sdk_FOUND AND dng_sdk_FOUND)
            set(_rawgl_dng_sdk_found ON)
        endif()
        rawgl_report_dependency("dng_sdk" ON "${_rawgl_dng_sdk_found}" "config/package")

        set(_rawgl_libheif_found OFF)
        if(DEFINED libheif_FOUND AND libheif_FOUND)
            set(_rawgl_libheif_found ON)
        elseif(DEFINED Libheif_FOUND AND Libheif_FOUND)
            set(_rawgl_libheif_found ON)
        endif()
        rawgl_report_dependency("libheif" ON "${_rawgl_libheif_found}" "config/package")

        rawgl_any_target_found(_rawgl_libuhdr_found libuhdr::libuhdr)
        rawgl_report_dependency("libuhdr" ON "${_rawgl_libuhdr_found}" "${_rawgl_libuhdr_found_PROVIDER}")

        rawgl_any_target_found(_rawgl_openjpeg_found openjp2 OpenJPEG::OpenJPEG openjpeg)
        rawgl_report_dependency("OpenJPEG" ON "${_rawgl_openjpeg_found}" "${_rawgl_openjpeg_found_PROVIDER}")

        if(RAWGL_HARFBUZZ_LIBRARY)
            rawgl_report_dependency("HarfBuzz" ON ON "${RAWGL_HARFBUZZ_LIBRARY}")
        else()
            rawgl_report_dependency("HarfBuzz" ON OFF "")
        endif()

        rawgl_any_target_found(_rawgl_webp_found WebP::webp WebP::webpdemux WebP::libwebpmux)
        rawgl_report_dependency("WebP" ON "${_rawgl_webp_found}" "${_rawgl_webp_found_PROVIDER}")

        rawgl_any_target_found(_rawgl_sharpyuv_found sharpyuv::sharpyuv)
        rawgl_report_dependency("SharpYUV" ON "${_rawgl_sharpyuv_found}" "${_rawgl_sharpyuv_found_PROVIDER}")
    elseif(WIN32)
        rawgl_any_target_found(_rawgl_zlib_found ZLIB::ZLIB ZLIB::ZLIBSTATIC)
        rawgl_report_dependency("ZLIB" ON "${_rawgl_zlib_found}" "${_rawgl_zlib_found_PROVIDER}")

        rawgl_any_target_found(_rawgl_png_found PNG::PNG PNG::png_static)
        rawgl_report_dependency("PNG" ON "${_rawgl_png_found}" "${_rawgl_png_found_PROVIDER}")

        rawgl_any_target_found(_rawgl_jpeg_found JPEG::JPEG libjpeg-turbo::jpeg-static)
        rawgl_report_dependency("JPEG" ON "${_rawgl_jpeg_found}" "${_rawgl_jpeg_found_PROVIDER}")

        rawgl_any_target_found(_rawgl_tiff_found TIFF::TIFF TIFF::tiff)
        rawgl_report_dependency("TIFF" ON "${_rawgl_tiff_found}" "${_rawgl_tiff_found_PROVIDER}")

        rawgl_any_target_found(_rawgl_gif_found GIF::GIF GIFLIB::gif GIFLIB::GIFLIB)
        rawgl_report_dependency("GIF/giflib" ON "${_rawgl_gif_found}" "${_rawgl_gif_found_PROVIDER}")

        rawgl_any_target_found(_rawgl_ptex_found Ptex::Ptex_static Ptex::Ptex Ptex)
        rawgl_report_dependency("Ptex" ON "${_rawgl_ptex_found}" "${_rawgl_ptex_found_PROVIDER}")

        rawgl_any_target_found(_rawgl_openjpeg_found openjp2 OpenJPEG::OpenJPEG openjpeg)
        rawgl_report_dependency("OpenJPEG" ON "${_rawgl_openjpeg_found}" "${_rawgl_openjpeg_found_PROVIDER}")

        set(_rawgl_libheif_found OFF)
        if(DEFINED libheif_FOUND AND libheif_FOUND)
            set(_rawgl_libheif_found ON)
        elseif(DEFINED Libheif_FOUND AND Libheif_FOUND)
            set(_rawgl_libheif_found ON)
        endif()
        rawgl_report_dependency("libheif" ON "${_rawgl_libheif_found}" "config/package")

        set(_rawgl_opencolorio_found OFF)
        if(DEFINED OpenColorIO_FOUND AND OpenColorIO_FOUND)
            set(_rawgl_opencolorio_found ON)
        endif()
        rawgl_report_dependency("OpenColorIO" ON "${_rawgl_opencolorio_found}" "config/package")

        set(_rawgl_openexr_found OFF)
        if(DEFINED OpenEXR_FOUND AND OpenEXR_FOUND)
            set(_rawgl_openexr_found ON)
        elseif(TARGET OpenEXR::OpenEXR)
            set(_rawgl_openexr_found ON)
        endif()
        rawgl_report_dependency("OpenEXR" ON "${_rawgl_openexr_found}" "config/package")

        rawgl_any_target_found(_rawgl_fmt_found fmt::fmt)
        rawgl_report_dependency("fmt" ON "${_rawgl_fmt_found}" "${_rawgl_fmt_found_PROVIDER}")

        rawgl_any_target_found(_rawgl_pugixml_found pugixml::pugixml pugixml)
        rawgl_report_dependency("pugixml" ON "${_rawgl_pugixml_found}" "${_rawgl_pugixml_found_PROVIDER}")

        rawgl_any_target_found(_rawgl_freetype_found Freetype::Freetype)
        rawgl_report_dependency("freetype" ON "${_rawgl_freetype_found}" "${_rawgl_freetype_found_PROVIDER}")

        rawgl_any_target_found(_rawgl_yaml_found yaml-cpp)
        rawgl_report_dependency("yaml-cpp" ON "${_rawgl_yaml_found}" "${_rawgl_yaml_found_PROVIDER}")

        rawgl_any_target_found(_rawgl_minizip_found minizip-ng::minizip-ng minizip-ng)
        rawgl_report_dependency("minizip-ng" ON "${_rawgl_minizip_found}" "${_rawgl_minizip_found_PROVIDER}")

        rawgl_any_target_found(_rawgl_expat_found EXPAT::EXPAT expat::expat)
        rawgl_report_dependency("expat" ON "${_rawgl_expat_found}" "${_rawgl_expat_found_PROVIDER}")

        rawgl_any_target_found(_rawgl_pystring_found pystring::pystring)
        rawgl_report_dependency("pystring" ON "${_rawgl_pystring_found}" "${_rawgl_pystring_found_PROVIDER}")

        rawgl_any_target_found(_rawgl_zstd_found ZSTD::ZSTD zstd::libzstd_static zstd::libzstd)
        rawgl_report_dependency("zstd" ON "${_rawgl_zstd_found}" "${_rawgl_zstd_found_PROVIDER}")

        rawgl_any_target_found(_rawgl_deflate_found Deflate::Deflate libdeflate::libdeflate_static)
        rawgl_report_dependency("libdeflate" ON "${_rawgl_deflate_found}" "${_rawgl_deflate_found_PROVIDER}")

        rawgl_any_target_found(_rawgl_liblzma_found liblzma::liblzma)
        rawgl_report_dependency("liblzma" ON "${_rawgl_liblzma_found}" "${_rawgl_liblzma_found_PROVIDER}")

        rawgl_any_target_found(_rawgl_webp_found WebP::webp WebP::webpdemux WebP::libwebpmux)
        rawgl_report_dependency("WebP" ON "${_rawgl_webp_found}" "${_rawgl_webp_found_PROVIDER}")

        rawgl_any_target_found(_rawgl_libuhdr_found libuhdr::libuhdr)
        rawgl_report_dependency("libuhdr" ON "${_rawgl_libuhdr_found}" "${_rawgl_libuhdr_found_PROVIDER}")

        rawgl_any_target_found(_rawgl_harfbuzz_found HarfBuzz::HarfBuzz harfbuzz::harfbuzz)
        rawgl_report_dependency("HarfBuzz" ON "${_rawgl_harfbuzz_found}" "${_rawgl_harfbuzz_found_PROVIDER}")

        rawgl_any_target_found(_rawgl_bzip2_found BZip2::BZip2)
        rawgl_report_dependency("BZip2" ON "${_rawgl_bzip2_found}" "${_rawgl_bzip2_found_PROVIDER}")

        rawgl_any_target_found(_rawgl_aom_found aom AOM::aom)
        rawgl_report_dependency("AOM" ON "${_rawgl_aom_found}" "${_rawgl_aom_found_PROVIDER}")

        rawgl_any_target_found(_rawgl_icu_found ICU::uc ICU::i18n ICU::data)
        rawgl_report_dependency("ICU" ON "${_rawgl_icu_found}" "${_rawgl_icu_found_PROVIDER}")

        message(STATUS "    Windows static libraries:")
        rawgl_report_file_dependency("DNG SDK Release" "${RAWGL_WINDOWS_DNG_LIBRARY_RELEASE}")
        rawgl_report_file_dependency("DNG SDK Debug" "${RAWGL_WINDOWS_DNG_LIBRARY_DEBUG}")
        rawgl_report_file_dependency("XMP Core Release" "${RAWGL_WINDOWS_XMP_CORE_LIBRARY_RELEASE}")
        rawgl_report_file_dependency("XMP Core Debug" "${RAWGL_WINDOWS_XMP_CORE_LIBRARY_DEBUG}")
        rawgl_report_file_dependency("XMP Files Release" "${RAWGL_WINDOWS_XMP_FILES_LIBRARY_RELEASE}")
        rawgl_report_file_dependency("XMP Files Debug" "${RAWGL_WINDOWS_XMP_FILES_LIBRARY_DEBUG}")
    endif()

    message(STATUS "    Python:")
    if(RAWGL_BUILD_PYTHON)
        set(_rawgl_python_found OFF)
        set(_rawgl_python_provider "")
        if(DEFINED RAWGL_PYTHON_VERSION AND RAWGL_PYTHON_VERSION)
            set(_rawgl_python_found ON)
            set(_rawgl_python_provider "Python ${RAWGL_PYTHON_VERSION}")
        elseif(DEFINED Python_VERSION AND Python_VERSION)
            set(_rawgl_python_found ON)
            set(_rawgl_python_provider "Python ${Python_VERSION}")
        elseif(DEFINED Python_EXECUTABLE AND Python_EXECUTABLE)
            set(_rawgl_python_found ON)
            set(_rawgl_python_provider "${Python_EXECUTABLE}")
        endif()
        rawgl_report_dependency("Python" ON "${_rawgl_python_found}" "${_rawgl_python_provider}")
        if(DEFINED Python_EXECUTABLE AND Python_EXECUTABLE)
            message(STATUS "      Python_EXECUTABLE: ${Python_EXECUTABLE}")
        endif()
        if(DEFINED RAWGL_PYTHON_INCLUDE_DIR_EFFECTIVE AND RAWGL_PYTHON_INCLUDE_DIR_EFFECTIVE)
            message(STATUS "      Python include dir: ${RAWGL_PYTHON_INCLUDE_DIR_EFFECTIVE}")
        endif()
        if(WIN32)
            if(DEFINED RAWGL_PYTHON_LIBRARY_RELEASE_EFFECTIVE AND RAWGL_PYTHON_LIBRARY_RELEASE_EFFECTIVE)
                rawgl_report_file_dependency("Python import library Release" "${RAWGL_PYTHON_LIBRARY_RELEASE_EFFECTIVE}")
            endif()
            if(DEFINED RAWGL_PYTHON_LIBRARY_DEBUG_EFFECTIVE AND RAWGL_PYTHON_LIBRARY_DEBUG_EFFECTIVE)
                rawgl_report_file_dependency("Python import library Debug" "${RAWGL_PYTHON_LIBRARY_DEBUG_EFFECTIVE}")
            endif()
        elseif(DEFINED RAWGL_PYTHON_LIBRARY_EFFECTIVE AND RAWGL_PYTHON_LIBRARY_EFFECTIVE)
            rawgl_report_file_dependency("Python library" "${RAWGL_PYTHON_LIBRARY_EFFECTIVE}")
        endif()

        set(_rawgl_nanobind_found OFF)
        set(_rawgl_nanobind_provider "")
        if(DEFINED RAWGL_NANOBIND_FOUND AND RAWGL_NANOBIND_FOUND)
            set(_rawgl_nanobind_found ON)
            set(_rawgl_nanobind_provider "${RAWGL_NANOBIND_PROVIDER}")
        elseif(DEFINED nanobind_FOUND AND nanobind_FOUND)
            set(_rawgl_nanobind_found ON)
            if(DEFINED nanobind_DIR AND nanobind_DIR)
                set(_rawgl_nanobind_provider "${nanobind_DIR}")
            else()
                set(_rawgl_nanobind_provider "system (config)")
            endif()
        elseif(DEFINED nanobind_DIR AND nanobind_DIR)
            set(_rawgl_nanobind_found ON)
            set(_rawgl_nanobind_provider "${nanobind_DIR}")
        endif()
        rawgl_report_dependency("nanobind" ON "${_rawgl_nanobind_found}" "${_rawgl_nanobind_provider}")
        if(RAWGL_PYTHON_BIND_CORE)
            if(WIN32)
                message(STATUS "      Python binding mode: real RawGL facade")
            else()
                message(STATUS "      Python binding mode: real RawGL facade (requires PIC-safe dependency stack)")
            endif()
        else()
            message(STATUS "      Python binding mode: scaffold only")
        endif()
    else()
        rawgl_report_dependency("Python" OFF OFF "")
        rawgl_report_dependency("nanobind" OFF OFF "")
    endif()
endfunction()
